apiVersion: v1
kind: Namespace
metadata:
  name: cloudpak
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"Key": "node-role.kubernetes.io/cloud-paks", "Operator": "Equal", "Value": "true", "Effect": "NoExecute"}]'
    scheduler.alpha.kubernetes.io/node-selector: node-role.kubernetes.io/cloud-paks=true