apiVersion: v1
kind: Namespace
metadata:
  name: ibm-spectrum-scale
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"Key": "node.ocs.openshift.io/storage", "Operator": "Equal", "Value": "true", "Effect": "NoSchedule"}]'