apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cluster-csi-drivers
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"effect":"NoSchedule", "key": "infra", "value": ""},{"Key": "node.ocs.openshift.io/storage", "Operator": "Equal", "Value": "true", "Effect": "NoSchedule"},{"Key": "fusion", "Operator": "Equal", "Value": "true", "Effect": "NoSchedule"}]'