apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management 
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"effect":"NoSchedule", "key": "infra", "value": ""}]'