apiVersion: v2
name: cnsa
description: Deployment of CNSA for Spevtrum Scale
type: application
version: 0.9.0
appVersion: "0.9.0"
dependencies:
  - name: cnsa
    version: 0.9.0
    repository: https://chechuironman.github.io/helm-repo/


