apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators
  annotations:
      scheduler.alpha.kubernetes.io/defaultTolerations: '[{"Key": "node-role.kubernetes.io/infra", "Operator": "Equal", "Value": "true", "Effect": "NoExecute"}]'
