apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
  annotations:
      scheduler.alpha.kubernetes.io/defaultTolerations: '[{"Key": "node-role.kubernetes.io/foundational-services", "Operator": "Equal", "Value": "true", "Effect": "NoExecute"},{"Key": "node-role.kubernetes.io/storage", "Operator": "Equal", "Value": "true", "Effect": "NoExecute"},{"Key": "node-role.kubernetes.io/cloud-paks", "Operator": "Equal", "Value": "true", "Effect": "NoExecute"},{"Key": "node-role.kubernetes.io/workers", "Operator": "Equal", "Value": "true", "Effect": "NoExecute"}]'
      # scheduler.alpha.kubernetes.io/node-selector: node-role.kubernetes.io/foundational-services=true