apiVersion: v1
kind: Namespace
metadata:
  name: aiops
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:  annotations:
    # openshift.io/sa.scc.uid-range: 1000710000/1
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"Key": "node-role.kubernetes.io/cloud-paks", "Operator": "Equal", "Value": "true", "Effect": "NoExecute"}]'
    scheduler.alpha.kubernetes.io/node-selector: node-role.kubernetes.io/cloud-paks=true